### ISSUE TITLE
IPv6 error

### ISSUE THREAD

**Issue by null321-jared** [jython234/JRakLibPlus#7]
I don't know if they switched Minecraft Pocket Edition to IPv6, or if they just changed it in a way so the byte shows up as a 6, but it's throwing the error that it isn't supported.

`328888 [RakNetServer] ERROR JRakLibPlus Server  - Fatal Exception, server has crashed! java.lang.UnsupportedOperationException: Can't read IPv6 address: Not Implemented
java.lang.UnsupportedOperationException: Can't read IPv6 address: Not Implemented
    at io.github.jython234.jraklibplus.nio.NioBuffer.getAddress(NioBuffer.java:146)
    at io.github.jython234.jraklibplus.protocol.minecraft.ClientHandshakePacket._decode(ClientHandshakePacket.java:55)
    at io.github.jython234.jraklibplus.protocol.RakNetPacket.decode(RakNetPacket.java:66)
    at io.github.jython234.jraklibplus.server.Session.handleEncapsulatedPacket(Session.java:376)
    at java.util.ArrayList.forEach(ArrayList.java:1249)
    at io.github.jython234.jraklibplus.server.Session.handleDataPacket(Session.java:305)
    at io.github.jython234.jraklibplus.server.Session.handlePacket(Session.java:273)
    at io.github.jython234.jraklibplus.server.RakNetServer.handlePacket(RakNetServer.java:260)
    at io.github.jython234.jraklibplus.server.RakNetServer.handlePackets(RakNetServer.java:184)
    at io.github.jython234.jraklibplus.server.RakNetServer.lambda$2(RakNetServer.java:154)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
    at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1540)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
    at io.github.jython234.jraklibplus.server.RakNetServer.tick(RakNetServer.java:153)
    at io.github.jython234.jraklibplus.server.RakNetServer.run(RakNetServer.java:126)
    at io.github.jython234.jraklibplus.server.ThreadedRakNetServer.access$0(ThreadedRakNetServer.java:1)
    at java.lang.Thread.run(Thread.java:745)
`
I did disable IPv6 on the client device to try to prevent it from using IPv6.
Also I found a new source for packet information. https://confluence.yawk.at/display/PEPROTOCOL/Game+Packets

**Comment by alejzeis** [comment]
Is there any way you can check if its using ipv6? (Try wireshark)

**Comment by null321-jared** [comment]
It appears to be, RakNet seems to be using IPv4 but when it switches to the other stuff it's IPv6
![image](https://cloud.githubusercontent.com/assets/12385687/19826348/b3c6637e-9d55-11e6-8db3-556de181ce62.png)

**Comment by alejzeis** [comment]
Yeah, then its the case that it doesnt know how to read v6, because I didnt
know how. Ill see if I can push a fix sometime soon. Are you using this via
maven?

On Oct 28, 2016 8:30 PM, "lizardfreak321" notifications@github.com wrote:

It appears to be, RakNet seems to be using IPv4 but when it switches to the
other stuff it's IPv6
[image: image]
https://cloud.githubusercontent.com/assets/12385687/19826348/b3c6637e-9d55-11e6-8db3-556de181ce62.png

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
https://github.com/jython234/JRakLibPlus/issues/7#issuecomment-257062766,
or mute the thread

**Comment by null321-jared** [comment]
I cloned it from the repository and have it as a project in eclipse.
